#!/usr/bin/env perl

use strict;
use warnings;

sub main {
    my ($upstream, $branch) = @_;

    $upstream = 2  unless ($upstream);
    $branch   = '' unless ($branch);

    if ($upstream =~ /^[0-9]+$/) {
        $upstream = "HEAD~$upstream";
    } elsif ($upstream =~ /^[~^][0-9~^]*$/) {
        $upstream = "HEAD$upstream";
    }

    return "git rebase -i $upstream $branch";
}

if ($0 eq __FILE__) {
    exec main(@ARGV);
}

1;
__END__

=head1 NAME

git-irebase - alias for git rebase -i

=head1 SYNOPSIS

  $ git irebase [<upstream>] [<branch>]
  $ git ir      [<upstream>] [<branch>]

=head1 DESCRIPTION

  git irebase           -> git rebase -i HEAD~2
  git irebase 5         -> git rebase -i HEAD~5
  git irebase ^^^       -> git rebase -i HEAD^^^
  git irebase 2 develop -> git rebase -i HEAD~2 develop

=head1 INSTALL

  $ git clone https://github.com/yosugi/git-irebase.git
  $ export PATH=./git-irebase:$PATH
  $ git irebase

=head1 AUTHOR

yosugi

=head1 LICENSE

MIT License (http://opensource.org/licenses/mit-license.php)

=cut

